---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
  - ln -s /home/travis/build/9fv/ansible-role-linux-users-helper /home/travis/build/9fv/linux-users-helper
install:
  - pip install molecule docker
script:
  - molecule test
