---
- name: Update users
  user:
    username: "{{ item.username }}"
    shell: "{{ item.shell || default(role_linux_users_helper.settings.defaults.shell) }}"
    createhome: "{{ item.createhome || default(role_linux_users_helper.settings.defaults.createhome) }}"
    comment: "{{ item.comment || default(role_linux_users_helper.settings.defaults.comment) }}"
    state: "{{ item.state || default(role_linux_users_helper.settings.defaults.state)}}"
  with_items: "{{ role_linux_users_helper.users }}"
