---
- name: Update users
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell | default(role_linux_users_helper_settings.defaults.shell) }}"
    createhome: "{{ item.createhome | default(role_linux_users_helper_settings.defaults.createhome) }}"
    comment: "{{ item.comment | default(role_linux_users_helper_settings.defaults.comment) }}"
    state: "{{ item.state | default(role_linux_users_helper_settings.defaults.state)}}"
  with_items: "{{ role_linux_users_helper.users }}"
