---
dependency:
  name: galaxy
driver:
  name: docker
docker:
  containers:
    - name: node1
      image: debian:stretch
lint:
  name: yamllint
platforms:
  - name: node1
    image: debian:stretch
provisioner:
  name: ansible
  # log: true
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
ansible:
