---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-linux-users-helper
      vars:
        role_linux_users_helper:
          users:
            - name: user1
              password: mysecretpassword
              state: present
            - name: user2
              password: mysecretpassword
              shell: /bin/sh
            - name: user3
              password: mysecretpassword
              state: absent
